# Generated by Django 3.0.3 on 2020-02-21 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_auto_20200221_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='cellphone',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(regex='(\\(?\\d{2}\\)?\\s)?(\\d{4,5}\\-?\\d{4})')]),
        ),
    ]
