# Generated by Django 3.0.3 on 2020-02-21 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_auto_20200221_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='cep',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(regex='(\\d{3}[.\\s]?\\d{3}[.\\s]?\\d{3}[-.\\s]?\\d{2})')]),
            preserve_default=False,
        ),
    ]
