# Generated by Django 3.0.3 on 2020-02-28 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_demand_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='cep',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='([0-9]{5}-[\\d]{3})')]),
        ),
    ]
